support m/888' path
Zondax/ledger-blockstack pull request #104
Opened 2022-04-12 19:08 UTC by neithanmo

this closes #103

2022-04-15 14:04 UTC, jleni requested changes

2022-04-15 14:04 UTC, jleni commented on app/src/common/app_main.c
> +    const bool identity_path = hdPath[0] == HDPATH_0_AUTH;
This could be an issue.
We need to be sure that it is not possible to use the identity path in other APDUs.

I would recommend splitting this check in two independent functions and run the respective checks in each APDU.

We dont want people to sign txs with 888 or tokens with the normal path

2022-04-15 14:04 UTC, jleni commented on app/src/common/app_main.c
> +    const bool identity_path = hdPath[0] == HDPATH_0_AUTH;
can we check path length too? now we have different lengths depending on the start

2022-04-17 17:37 UTC, neithanmo commented on app/src/common/app_main.c
> +    const bool identity_path = hdPath[0] == HDPATH_0_AUTH;
yes, i agree it is better to handle the path separately. 
done !

2022-04-25 12:54 UTC, merged